apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: contoso
  name: contoso
  namespace: contoso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contoso
  template:
    metadata:
      labels:
        app: contoso
    spec:
      containers:
      - image: gcr.io/jasondel-test-project/cymbal:v4
        imagePullPolicy: IfNotPresent
        name: contoso-container
        volumeMounts: 
        - name: connection-strings
          mountPath: "/inetpub/wwwroot/cymbaluniversity/secret"
          readOnly: true        
        ports:
        - containerPort: 80
          protocol: TCP
      nodeSelector:
        kubernetes.io/os: windows
        cloud.google.com/gke-os-distribution: windows_sac
      volumes:
      - name: connection-strings
        secret:
          secretName: connection-strings
      restartPolicy: Always